services:

    gewebe_sylius_vat_plugin.form.extension.address:
        class: Gewebe\SyliusVATPlugin\Form\Extension\AddressTypeExtension
        arguments:
            - '@gewebe_sylius_vat_plugin.vat_number_validator_config'
        tags:
            - { name: form.type_extension, extended_type: Sylius\Bundle\AddressingBundle\Form\Type\AddressType }

    gewebe_sylius_vat_plugin.form.extension.shop_billing_data:
        class: Gewebe\SyliusVATPlugin\Form\Extension\ShopBillingDataTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Sylius\Bundle\CoreBundle\Form\Type\ShopBillingDataType }

    gewebe_sylius_vat_plugin.form.modifier.vat_number_address_form_values:
        class: Gewebe\SyliusVATPlugin\Form\Modifier\VatNumberAddressFormValuesModifier
        tags:
            - { name: sylius_shop.modifier.address_form_values }
