services:

    gewebe_sylius_vat_plugin.vat_number_validator:
        class: Gewebe\SyliusVATPlugin\Validator\Constraints\VatNumberValidator
        arguments:
            - '@gewebe_sylius_vat_plugin.vat_number_validator_provider'
            - '@gewebe_sylius_vat_plugin.vat_number_validator_config'
        tags:
            - { name: validator.constraint_validator }

    gewebe_sylius_vat_plugin.vat_number_validator_config:
        class: Gewebe\SyliusVATPlugin\Config\VatNumberValidatorConfig
        # All arguments are set from the bundle configuration in GewebeSyliusVATExtension::load()
        arguments:
            - !abstract 'required.default'
            - !abstract 'required.company'
            - !abstract 'required.countries'
            - !abstract 'validate.format'
            - !abstract 'validate.country'
            - !abstract 'validate.registration'
            - !abstract 'validate.on_service_unavailable'
            - !abstract 'revalidate.on_login'
            - !abstract 'revalidate.expiration_days'

    gewebe_sylius_vat_plugin.vat_number_validator_provider:
        class: Gewebe\SyliusVATPlugin\Vat\Number\VatNumberValidatorProvider
        arguments:
            - !tagged_iterator gewebe_sylius_vat_plugin.zone_vat_number_validator

    gewebe_sylius_vat_plugin.eu_vat_number_validator:
        class: Gewebe\SyliusVATPlugin\Vat\Number\Validator\EuVatNumberValidator
        arguments:
            - '@gewebe_sylius_vat_plugin.ibericode_vat.validator'
        tags:
            - { name: gewebe_sylius_vat_plugin.zone_vat_number_validator }

    gewebe_sylius_vat_plugin.ibericode_vat.validator:
        class: Ibericode\Vat\Validator
