services:
    php:
        image: ghcr.io/sylius/sylius-php:8.3-alpine
    mysql:
        image: mysql:8.4
        platform: linux/amd64
        healthcheck:
            test: '/usr/bin/mysql --user=root --password=root --execute "SHOW databases;"'
            timeout: 3s
            interval: 1s
            retries: 10
        environment:
            MYSQL_ROOT_PASSWORD: root
        cap_add:
            - SYS_NICE # prevent "mbind: Operation not permitted" errors
    nginx:
        image: ghcr.io/sylius/sylius-nginx:latest
        depends_on:
            -   php
    mailhog:
        # do not use in production!
        image: mailhog/mailhog:latest
