sylius_twig_hooks:
    hooks:
        'sylius_admin.channel.create.content.form.sections.shop_billing_data':
            vat_number:
                template: '@GewebeSyliusVATPlugin/admin/channel/form/sections/shop_billing_data/vat_number.html.twig'
                priority: -100
